name: developer
description: Conreality Developer app for Android and iOS.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.5.4-hotfix.2 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  material_design_icons_flutter: ^3.2.3695
  package_info: ^0.4.0+4

  # See: https://github.com/transistorsoft/flutter_background_geolocation
  flutter_background_geolocation: ^1.0.10

  # See: https://github.com/conreality/conreality-plugins/tree/master/conreality_headset
  conreality_headset:
    git:
      url: https://github.com/conreality/conreality-plugins.git
      path: conreality_headset

  # See: https://github.com/conreality/conreality-widgets/tree/master/conreality_camera
  conreality_camera:
    git:
      url: https://github.com/conreality/conreality-widgets.git
      path: conreality_camera

  # See: https://github.com/conreality/conreality-widgets/tree/master/conreality_chat
  conreality_chat:
    git:
      url: https://github.com/conreality/conreality-widgets.git
      path: conreality_chat

  # See: https://github.com/conreality/conreality-widgets/tree/master/conreality_compass
  conreality_compass:
    git:
      url: https://github.com/conreality/conreality-widgets.git
      path: conreality_compass

  # See: https://github.com/conreality/conreality-widgets/tree/master/conreality_countdown
  conreality_countdown:
    git:
      url: https://github.com/conreality/conreality-widgets.git
      path: conreality_countdown

  # See: https://github.com/conreality/conreality-widgets/tree/master/conreality_dosimeter
  conreality_dosimeter:
    git:
      url: https://github.com/conreality/conreality-widgets.git
      path: conreality_dosimeter

  # See: https://github.com/conreality/conreality-widgets/tree/master/conreality_fonts
  conreality_fonts:
    git:
      url: https://github.com/conreality/conreality-widgets.git
      path: conreality_fonts

  # See: https://github.com/conreality/conreality-widgets/tree/master/conreality_gamepad
  conreality_gamepad:
    git:
      url: https://github.com/conreality/conreality-widgets.git
      path: conreality_gamepad

  # See: https://github.com/conreality/conreality-widgets/tree/master/conreality_icons
  conreality_icons:
    git:
      url: https://github.com/conreality/conreality-widgets.git
      path: conreality_icons

  # See: https://github.com/conreality/conreality-widgets/tree/master/conreality_joystick
  conreality_joystick:
    git:
      url: https://github.com/conreality/conreality-widgets.git
      path: conreality_joystick

  # See: https://github.com/conreality/conreality-widgets/tree/master/conreality_login
  conreality_login:
    git:
      url: https://github.com/conreality/conreality-widgets.git
      path: conreality_login

  # See: https://github.com/conreality/conreality-widgets/tree/master/conreality_logo
  conreality_logo:
    git:
      url: https://github.com/conreality/conreality-widgets.git
      path: conreality_logo

  # See: https://github.com/conreality/conreality-widgets/tree/master/conreality_map
  conreality_map:
    git:
      url: https://github.com/conreality/conreality-widgets.git
      path: conreality_map

  # See: https://github.com/conreality/conreality-widgets/tree/master/conreality_replay
  conreality_replay:
    git:
      url: https://github.com/conreality/conreality-widgets.git
      path: conreality_replay

  # See: https://github.com/conreality/conreality-widgets/tree/master/conreality_tracker
  conreality_tracker:
    git:
      url: https://github.com/conreality/conreality-widgets.git
      path: conreality_tracker

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - scripts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
